"""Render a :class:`~magi.mapper.Profile` as a Kconfig fragment file.

The output format matches what ``scripts/kconfig/merge_config.sh`` (part
of every Linux kernel source tree) expects: one ``CONFIG_FOO=y`` per
line. This lets the fragment be consumed either by MAGI's own builder
or manually by anyone who prefers to run merge_config.sh themselves.

IMPORTANT: the fragment must not contain per-option comment lines that
repeat the option's own name (e.g. ``# CONFIG_NET: ...`` directly above
``CONFIG_NET=y``). merge_config.sh locates each option's current value
with ``grep -w $CFG $file``, which is a plain substring/word match, not
comment-aware -- a comment mentioning the same CONFIG_ token matches
too, and gets concatenated with the real line, corrupting the merge.
This was caught by running an actual kernel source tree's
merge_config.sh against MAGI's output (see tests/test_kernel_build.py
and the project's real-kernel validation notes), not by unit tests
alone. The human-readable rationale for each option is still available
via ``Profile.trace`` / ``magi analyze`` and :func:`render_explanation`
-- it is just kept out of the machine-consumed fragment file.
"""

from __future__ import annotations

from pathlib import Path

from ..mapper import Profile

HEADER = (
    "# Generated by MAGI -- do not edit by hand.\n"
    "# Re-run `magi build` to regenerate after the source tree changes.\n"
    "# Run `magi build --explain` to see why each option was included.\n"
)


def render_fragment(profile: Profile) -> str:
    """Pure merge_config.sh-compatible fragment: header comment block,
    then exactly one ``CONFIG_FOO=y`` per line and nothing else."""
    lines = [HEADER]
    lines.extend(f"{opt}=y" for opt in profile.options)
    lines.append("")
    return "\n".join(lines)


def render_explanation(profile: Profile) -> str:
    """Human-readable companion report: which capability caused each
    option to be included. Never fed to merge_config.sh."""
    lines = ["# why each option was included\n"]
    for opt in profile.options:
        lines.append(f"{opt}")
        for reason in profile.trace.get(opt, []):
            lines.append(f"    - {reason}")
    lines.append("")
    return "\n".join(lines)


def write_fragment(profile: Profile, out_path: Path) -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_fragment(profile), encoding="utf-8")
    return out_path
