"""Render a :class:`~magi.mapper.Profile` as a Kconfig fragment file.

The output format matches what ``scripts/kconfig/merge_config.sh`` (part
of every Linux kernel source tree) expects: one ``CONFIG_FOO=y`` per
line. This lets the fragment be consumed either by MAGI's own builder
or manually by anyone who prefers to run merge_config.sh themselves.
"""

from __future__ import annotations

from pathlib import Path

from ..mapper import Profile

HEADER = (
    "# Generated by MAGI (https://github.com/) -- do not edit by hand.\n"
    "# Re-run `magi build` to regenerate after the source tree changes.\n"
)


def render_fragment(profile: Profile) -> str:
    lines = [HEADER]
    for opt in profile.options:
        reasons = profile.trace.get(opt, [])
        if reasons:
            lines.append(f"# {opt}: {reasons[0]}")
        lines.append(f"{opt}=y")
    lines.append("")
    return "\n".join(lines)


def write_fragment(profile: Profile, out_path: Path) -> Path:
    out_path = Path(out_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_fragment(profile), encoding="utf-8")
    return out_path
